name: anaconda-life-sciences
channels:
  - defaults
  - https://repo.anaconda.cloud/repo/community
  - https://repo.anaconda.cloud/repo/conda-forge
default_channels:
  - https://repo.anaconda.cloud/repo/main
  - https://repo.anaconda.cloud/repo/r
  - https://repo.anaconda.cloud/repo/msys2
dependencies:
  - python=3.11
  - rdkit
  - biopython
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - openpyxl
  - requests
  - tqdm
  - plotly
  - cufflinks
  - pymol-open-source
  - chembl_webresource_client
  - deepchem
  - tensorflow
  - keras
  - xgboost
  - lightgbm
  - catboost
  - scipy
  - statsmodels
  - bokeh
  - networkx
  - mlxtend
  - xlrd
  - beautifulsoup4
  - lxml
  - conda-pack
  - xmltodict
  - h5py
  - tables
  - zarr
  - dask
  - distributed
  - numba
  - cython
  - ipykernel
